### ISSUE TITLE
Erro de controle de estoque de recebimentos da maquina dispensadora

### ISSUE THREAD

**Issue by BrunoMine** [Lunovox/minertrade#1]
Existe um problema nas máquinas, quando não cabe mais itens recebidos pela venda, a máquina continua realizando a troca porem o dono da máquina não recebe o item pois o estoque de recebimento já está cheio. O certo seria a máquina bloquear a troca.

Alem disso tem um pequeno erro no termo _Estoque a Oferetar:_ (está escrito assim mesmo)

**Comment by Lunovox** [comment]
> a máquina continua realizando a troca porem o dono da máquina não recebe o item pois o estoque de recebimento já está cheio

Resolvido!

> erro no termo "Estoque a Oferetar"

Tradução Corrigida!

**Comment by Lunovox** [comment]
> a máquina continua realizando a troca porem o dono da máquina não recebe o item pois o estoque de recebimento já está cheio

Resolvido!

> erro no termo "Estoque a Oferetar"

Tradução Corrigida!
